on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Lint, SAST, SCA, IaC, and secret scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Scan
        uses: phronesis-labs/scan@v0.0.1
  
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Unit Test
        uses: phronesis-labs/unit-test@v0.0.1

  build:
    name: Build, scan, tag, and publish container image
    runs-on: ubuntu-latest
    needs: [scan, unit-test]
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build
        uses: phronesis-labs/build@v0.0.1
